### ISSUE TITLE
Code and models are missing

### ISSUE THREAD

**Issue by ddofer** [chao1224/ProteinDT#1]
Hi, I read the paper - but I see the repo is empty of code or models.
Notably, I want to see if your textual pretraining data filtered out cases that appear (or are similar, by BLAST or the like) to any in the TAPE eval set. (e.g. like we did in ProteinBERT  https://github.com/nadavbra/protein_bert )

**Comment by chao1224** [comment]
Hi @ddofer,

Thank you for the questions.
- We will release the codes and models once our manuscript is officially published.
- To your second question, we double-checked the SwissProtCLAP and TAPE datasets (train & eval & test), and there are no shared protein sequences.

**Comment by Amelie-Schreiber** [comment]
When will the paper be published and when will the code be subsequently released?

**Comment by chao1224** [comment]
Hi @Amelie-Schreiber, our manuscript is now in submission. We will release the code once it is accepted. Meanwhile, you can check the latest version [here](https://arxiv.org/abs/2302.04611).
