### ISSUE TITLE
Remove references to non-existent code

### ISSUE THREAD

**Issue by agitter** [chao1224/ProteinDT#3]
I started looking through the code and was slowed down because some files import other modules that no longer exist. For example `model_LatentDiffusionDecoder.py` has
```python
from ProteinDT.models.model_SDE import VESDE, VPSDE
```
but I don't see a `model_SDE.py` file.

Using an IDE or linter to remove imports like this would improve readability.

**Comment by chao1224** [comment]
Thanks @agitter for noticing this! I have fixed this in #6.
